CREATE TABLE Orders (
    Id UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
    Code VARCHAR(160) NOT NULL,
    CustomerId UNIQUEIDENTIFIER NOT NULL,
    Discount DECIMAL(18,2) NOT NULL,
    TotalPrice DECIMAL(18,2) NOT NULL,
    CreatedAt DATETIME2 NOT NULL,
    OrderStatus INT NOT NULL,
    Street VARCHAR(160),
    Number VARCHAR(160),
    AdditionalInfo VARCHAR(160),
    Neighborhood VARCHAR(160),
    ZipCode VARCHAR(160),
    City VARCHAR(160),
    State VARCHAR(160),
);

CREATE TABLE OrderItens (
    Id UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
    OrderId UNIQUEIDENTIFIER NOT NULL,
    ProductId UNIQUEIDENTIFIER NOT NULL,
    ProductName VARCHAR(160) NOT NULL,
    Quantity INT NOT NULL,
    UnitValue DECIMAL(18,2) NOT NULL,
    ProductImage VARCHAR(160),
    FOREIGN KEY (OrderId) REFERENCES Orders(Id)
);

CREATE INDEX IX_OrderItens_OrderId ON OrderItens(OrderId);
